# ref: https://github.com/actions/runner-images
name: amd64 Windows

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

# Building using the github runner environement directly.
jobs:
  native:
    strategy:
      matrix:
        # VS-2022 broken see https://github.com/bazelbuild/bazel/issues/18592
        runner: [windows-2022]
      fail-fast: false # Don't cancel all jobs if one fails.
    name: ${{matrix.runner}}•Bazel
    runs-on: ${{matrix.runner}}
    steps:
      - uses: actions/checkout@v5
      - name: Install Bazel
        run: choco install bazel
      - name: Check Bazel
        run: bazel version
      - name: Build
        run: >
          bazel build
          -c opt
          --subcommands=pretty_print
          ...
      - name: Test
        run: >
          bazel test
          -c opt
          --test_output=errors
          ...

  amd64_windows_bazel:
    runs-on: ubuntu-latest
    needs: native
    steps:
      - uses: actions/checkout@v5
