# ref: https://github.com/actions/virtual-environments
name: amd64 Windows

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  windows:
    strategy:
      matrix:
        # VS-2022 broken see https://github.com/bazelbuild/bazel/issues/18592
        runner: [windows-2022, windows-2019]
      fail-fast: false # Don't cancel all jobs if one fails.
    runs-on: ${{ matrix.runner }}
    #runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Bazel
      run: choco install bazel
    - name: Check Bazel
      run: bazel version
    - name: Build
      run: >
        bazel build
        -c opt
        --cxxopt="-std:c++20"
        --subcommands=true
        ...
    - name: Test
      run: >
        bazel test
        -c opt
        --cxxopt="-std:c++20"
        --test_output=all
        ...
